let headers = [
    {
        name:'Company',
        propName:'company'
    },
    {
        name:'Company',
        propName:'gender'
    },
    {
        name:'Company',
        propName:'category'
    },
    {
        name:'Company',
        propName:'subCategory'
    },
    {
        name:'Company',
        propName:'ag'
    },
    {
        name:'Company',
        propName:'brandType'
    },
    {
        name:'Company',
        propName:'brandName'
    },
    {
        name:'Company',
        propName:'quota'
    },
    {
        name:'Company',
        propName:'limit'
    },
    {
        name:'Company',
        propName:'closing'
    },
    {
        name:'Company',
        propName:'onWay'
    },
    {
        name:'Company',
        propName:'sale'
    },
    {
        name:'Company',
        propName:'closing'
    },
    {
        name:'Company',
        propName:'balanceLimit'
    },
    {
        name:'Company',
        propName:'avgQuota'
    },
    {
        name:'Company',
        propName:'saleQuota'
    },
    {
        name:'Company',
        propName:'closingQuota'
    },
    {
        name:'Company',
        propName:'excessShort'
    },
    {
        name:'Company',
        propName:'closingSale'
    }
]

let total=[
    {
        value:10000,
        propName:'quota'
    },
    {
        value:10000,
        propName:'limit'
    },
    {
        value:10000,
        propName:'closing'
    },
    {
        value:10000,
        propName:'onWay'
    },
    {
        value:10000,
        propName:'sale'
    },
    {
        value:10000,
        propName:'closing'
    },
    {
        value:10000,
        propName:'balanceLimit'
    },
    {
        value:10000,
        propName:'avgQuota'
    },
    {
        value:10000,
        propName:'saleQuota'
    },
    {
        value:10000,
        propName:'closingQuota'
    },
    {
        value:10000,
        propName:'excessShort'
    },
    {
        value:10000,
        propName:'closingSale'
    }
]