export enum GETDROPDOWNLIST {
    NAME = "api/referencedata/name",
    PASSWORD = "api/referencedata/password",
    EMAILID = "api/referencedata/emailId",
    MOBILE_NO = "api/referencedata/mobileNo",
    SUB_CATEGORY = "api/referencedata/subcategory",
    SNAME = "api/referencedata/sname",
    AG = "api/referencedata/ag",
    COMPANY = "api/referencedata/company",
    BRAND_TYPE = "api/referencedata/brandType",
    GENDER = "api/referencedata/gender",
    BRAND_NAME = "api/referencedata/brandName",
    CATEGORY = "api/referencedata/category",
    ACNM = "api/referencedata/acnm",
    ACNAME = "api/referencedata/acname",
    ETPACNM = "api/referencedata/etpAcnm",
    SAPACNM = "api/referencedata/sapAcnm",
    ZONE = "api/referencedata/zone",
    STATE = "api/referencedata/state",
    CITY = "api/referencedata/city",
    MANAGER = "api/referencedata/manager",
    MANAGER_TYPE = "api/referencedata/managertype",
    CITY_MANAGER = "api/referencedata/manager/1",
    REGIONAL_MANAGER = "api/referencedata/manager/2",
    SHOWROOM_MANAGER = "api/referencedata/manager/3",
    SHOWROOM_TYPE = "api/referencedata/showroomtype",
    ROLE = "api/referencedata/role",
    USERNAME = "api/referencedata/userName",
}
export enum MASTERAPI {
    SHOWROOM = "api/master/showroom",
    PRODUCT = "api/master/product",
    COMPANY = "api/master/company",
    CATEGORY = "api/master/category",
    SUB_CATEGORY = "api/master/subcategory",
    AG = "api/master/ag",
    BRAND_NAME = "api/master/brandName",
    GENDER = "api/master/gender",
    BRAND_TYPE = "api/master/brandType",
    SHOWROOM_TYPE = "api/master/showroomtype",
    PERIOD = "api/master/period",
    MANAGER = "api/master/manager",
    ROLE = "api/master/role",
    USER = "api/master/user",
}